import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import LoginSuccessToast from "@/components/modules/home/Auth/LoginSuccessToast";
import { Providers } from "@/providers/providers";
import CartDrawerClient from "@/components/modules/card/CartDrawerClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tugi Bugi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased funnel-display bg-cream-100` }
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
         <Providers>
           {children}
           <CartDrawerClient />
         </Providers>
        </ThemeProvider>
        <Suspense fallback={null}>
          <LoginSuccessToast />
        </Suspense>
      </body>
    </html>
  );
}
